name: voteapp
description: A new Flutter project.

publish_to: 'none' # Remove this if you want to publish to pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0

  # Other packages
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
