name: voteapp
description: A new Flutter project.

publish_to: 'none' # Remove this if you want to publish to pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  image_picker: ^1.0.4

  # Other packages
  uuid: ^3.0.7
  fl_chart: ^0.63.0
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
